# https://hub.docker.com/_/microsoft-mssql-server
# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash

version: '3'
services:
  postgres:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'prisma123'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql:/var/opt/mssql
volumes:
  mssql:
