name: postgis-express
on: push

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    container: node:12.18.2-stretch

    services:
      postgres:
        image: postgis/postgis:12-2.5-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: typescript/postgis-express/node_modules
          key: geolocation-${{ hashFiles('typescript/postgis-express/package.json') }}
          restore-keys: |
            geolocation-
      
      - name: Run tests
        run: |
          cd typescript/postgis-express
          yarn
          yarn test
        env:
          CI: true
