name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:12.18.2-stretch

    services:
      postgres:
        image: postgis/postgis:12-2.5-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: test
        run: sh .github/scripts/test-all.sh
        env:
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
